spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.oauth.client-id=${SWAGGER_CLIENT_ID}
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.scopes=openid profile

security.clients.swagger.client-id=${SWAGGER_CLIENT_ID}
security.clients.swagger.redirect-uri=${SWAGGER_REDIRECT_URI}

security.clients.postman.client-id=${POSTMAN_CLIENT_ID}
security.clients.postman.redirect-uri=${POSTMAN_REDIRECT_URI}

security.logout.redirect-url=/swagger-ui/index.html

logging.level.org.springframework.security=DEBUG