spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.oauth.client-id=${SWAGGER_CLIENT_ID}
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.scopes=openid profile

security.clients.swagger.client-id=${SWAGGER_CLIENT_ID}
security.clients.swagger.redirect-uri=${SWAGGER_REDIRECT_URI}

security.clients.spa.client-id=${SPA_CLIENT_ID}
security.clients.spa.redirect-uri=${SPA_REDIRECT_URI}

security.logout.redirect-url=/

logging.level.org.springframework.security=INFO