ALTER TABLE tb_property ADD COLUMN transaction_type VARCHAR(20) NOT NULL DEFAULT 'SALE';
ALTER TABLE tb_property ADD COLUMN category VARCHAR(20) NOT NULL DEFAULT 'HOUSE';
ALTER TABLE tb_property ADD COLUMN available BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE tb_property DROP COLUMN type;
ALTER TABLE tb_property DROP COLUMN status;

ALTER TABLE tb_property ALTER COLUMN transaction_type DROP DEFAULT;
ALTER TABLE tb_property ALTER COLUMN category DROP DEFAULT;